---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
  labels:
    app: "html-scrabble"
    app.kubernetes.io/instance: html-scrabble
  name: "html-scrabble"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "html-scrabble:latest"
  resources: {}
  nodeSelector:
    kubernetes.io/os: linux
  triggers:
    - type: "ConfigChange"
  source:
    git:
      ref: master
      uri: https://github.com/atgreen/html-scrabble
    contextDir:
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: ubi8/nodejs-12
      forcePull: true
      noCache: true
    type: Docker
status:
  lastVersion: 0
